export const TestimonialData = [
  {
    id: '1',
    img: '/images/testimonial/testimonial1.png',
    details: `PRO GCC is, in fact, one of the finest PRO service providers in Dubai, according to our research. We're relieved that we've finally found the proper individuals to help us with our business. I would want to express my gratitude to PRO Services Dubai for providing me with outstanding service. Definitely worth a try!`,
    Name: 'Smith Dcusa',
    desig: 'Co-Founder',
    company: 'trendsoft',
  },
  {
    id: '2',
    img: '/images/testimonial/testimonial2.jpg',
    details: `Good business advisors. At a fair price, they give excellent service. Every new and experienced businessman should contact ProGcc.org for setting up a new business or developing an existing firm, and I highly recommend it.`,
    Name: 'Lora Smith Deo',
    desig: 'Executive',
    company: 'Company',
  },
  {
    id: '3',
    img: '/images/testimonial/testimonial3.png',
    details: `Exceptional service This firm has exceeded my expectations. They helped me build my firm from the ground up, and they've also assisted me with finance. As a result, I'd like to suggest this firm to anyone seeking for a corporate security, trading, or banking system.`,
    Name: 'Ana Richmono',
    desig: 'Creative Leader',
    company: 'cart Teach zone',
  },
  {
    id: '4',
    img: '/images/testimonial/testimonial4.jpg',
    details: `It was a pleasure working with ProGcc to register our firm on the Dubai mainland. Special appreciation to Mr. Ashaq, who looked after our company with professionalism and care during his tenure with the company. Excellent service for a reasonable price. Definitely worth a try.`,
    Name: 'Jerffy Brown',
    desig: 'Pogramming Guro',
    company: 'BlueTeach',
  },
  {
    id: '5',
    img: '/images/testimonial/testimonial1.png',
    details: `Thanks to ProGcc for providing a supportive and professional staff. Definitely recommended to anyone who is interested in setting up a business in the UAE.`,
    Name: 'Poaul Simson',
    desig: 'Manager',
    company: 'Stone Teach',
  },
  {
    id: '6',
    img: '/images/testimonial/testimonial4.jpg',
    details: `All of them are specialists in their respective fields. As a result of Mr. Ashaq's direction and leadership, they operate honestly with their clients and deliver top-notch quality service. You should contact ProGcc if you want to improve the overall performance of your company's operations. More power to you and your colleagues!`,
    Name: 'John D',
    desig: 'Manager',
    company: 'Company',
  },
]
